// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypyprwnpfseijepscfht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlweXByd25wZnNlaWplcHNjZmh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMzAwNjMsImV4cCI6MjA2MzkwNjA2M30.z3mKEnX2nkQX6KnIHVSTkn3KV6bMKGs-rmPvt4UzMT0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);